const fs = require('fs');
const path = require('path');

// Target directory for build
const BUILD_DIR = path.resolve(__dirname, '../dist');
const TEMPLATE_PATH = path.join(BUILD_DIR, 'index.html');

if (!fs.existsSync(TEMPLATE_PATH)) {
  console.error('Error: dist/index.html template not found. Run "npm run build" first.');
  process.exit(1);
}

// Read the baseline HTML template generated by Vite build
const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');

// Define SEO metadata, page-specific rich text, SSS (FAQs) and JSON-LD Schemas for each language set
const pages = {
  // ==========================================
  // TURKISH PAGES (Default / Root)
  // ==========================================
  '': {
    title: 'E-Ticaret Web Tasarım & Websitesi Geliştirme Uzmanı | Samer Allaham',
    description: 'Profesyonel e-ticaret web tasarım ve websitesi geliştirme hizmetleri. Shopify & İKAS ile yüksek dönüşümlü online mağaza kurulumu. İstanbul merkezli uzman — Samer Allaham.',
    keywords: 'e ticaret web tasarım, web tasarım, websitesi, shopify kurulumu türkiye, ikas e-ticaret sitesi, e-ticaret sitesi kurulumu, e-ticaret optimizasyon, shopify danışmanlık, samer allaham, e-ticaret büyüme uzmanı',
    canonical: 'https://www.samer.life/',
    lang: 'tr',
    content: `
      <h1>E-Ticaret Web Tasarım & Websitesi Geliştirme Uzmanı | Samer Allaham</h1>
      <p>Merhaba, ben Samer Allaham — İstanbul merkezli profesyonel e-ticaret web tasarım ve websitesi geliştirme uzmanı. Shopify ve İKAS platformlarında yüksek dönüşüm oranlı e-ticaret sistemleri kuruyorum.</p>
      <h2>E-Ticaret & Web Tasarım Hizmetlerim</h2>
      <ul>
        <li><strong>E-Ticaret Web Tasarım & Kurulumu (Shopify & İKAS):</strong> A'dan Z'ye profesyonel mağaza tasarımı, ödeme sistemleri ve kargo entegrasyonu.</li>
        <li><strong>Profesyonel Web Tasarım:</strong> React ve Next.js ile ultra hızlı, modern ve SEO uyumlu kurumsal websitesi tasarımı.</li>
        <li><strong>E-Ticaret Hız & Dönüşüm Optimizasyonu (CRO):</strong> Google Core Web Vitals skorlarınızı yükselterek sepet terki oranlarını düşüren teknik geliştirmeler.</li>
        <li><strong>Yapay Zeka Destekli Ürün Görseli & SEO İçerik:</strong> Stüdyo kalitesinde ürün arka plan tasarımları ve Google/AI uyumlu zengin ürün açıklamaları.</li>
        <li><strong>Stok ve Depo Entegrasyon Otomasyonu:</strong> Pazaryerleri, ERP ve e-ticaret siteniz arasında API tabanlı anlık stok senkronizasyonu.</li>
      </ul>
      <h2>Müşteri Yorumları</h2>
      <ul>
        <li><strong>Ahmet Y. (AIO Coffee CEO):</strong> "Samer ile checkout ve hız optimizasyonu üzerinde çalıştık. Dönüşüm oranımız %35 arttı. İş disiplini ve teknik bilgisi harika."</li>
        <li><strong>Elif K. (Moda Butiği Kurucusu):</strong> "Wordpress sitemizi İKAS altyapısına sorunsuz taşıdı. Sayfa hızımız 1.1 saniyeye düştü. Destek ve yönlendirmeleri için çok teşekkürler."</li>
        <li><strong>Omar B. (Global E-Ticaret Müdürü):</strong> "Shopify ve Trendyol arasındaki stok senkronizasyon yazılımını geliştirdi. Manuel hatalardan kaynaklanan cezalarımız tamamen bitti."</li>
      </ul>
    `
  },
  'web-tasarim': {
    title: 'Profesyonel Web Tasarım | Modern Websitesi Geliştirme — Samer',
    description: 'React & Next.js ile modern, hızlı ve SEO uyumlu web tasarım hizmetleri. Kurumsal websitesi, portfolyo ve e-ticaret web tasarımı.',
    keywords: 'web tasarım, web tasarım istanbul, profesyonel web tasarım, websitesi tasarımı, kurumsal web tasarım, modern web tasarım',
    canonical: 'https://www.samer.life/web-tasarim',
    lang: 'tr',
    content: `
      <h1>Profesyonel Web Tasarım Hizmetleri | Samer Allaham</h1>
      <p>React ve Next.js altyapıları ile modern, hızlı ve SEO uyumlu web tasarım ve websitesi geliştirme hizmetleri. İşletmenizin dijital varlığını güçlendirecek özel web çözümleri.</p>
    `
  },
  'e-ticaret-web-tasarim': {
    title: 'E-Ticaret Web Tasarım | Profesyonel Online Mağaza — Samer',
    description: 'E-ticaret web tasarım hizmetleri. Shopify & İKAS ile satış yapan, mobil uyumlu ve SEO dostu online mağaza websitesi tasarımı.',
    keywords: 'e ticaret web tasarım, e-ticaret web tasarım, online mağaza tasarımı, e-ticaret websitesi, shopify web tasarım, ikas web tasarım',
    canonical: 'https://www.samer.life/e-ticaret-web-tasarim',
    lang: 'tr',
    content: `
      <h1>E-Ticaret Web Tasarım | Profesyonel Online Mağaza Kurulumu</h1>
      <p>Shopify ve İKAS platformlarında yüksek dönüşümlü e-ticaret web tasarım ve online mağaza kurulum hizmetleri. Mobil uyumlu, hızlı ve satış odaklı websitesi tasarımları.</p>
    `
  },
  'eticaret-site-kurulumu': {
    title: 'E-Ticaret Site Kurulumu İstanbul | Shopify & İKAS Uzmanı — Samer',
    description: 'İstanbul\'da profesyonel e-ticaret sitesi kurulumu. Shopify, İKAS ve WooCommerce ile 3-7 günde yayına al. Fiyat için iletişime geç.',
    keywords: 'shopify kurulumu istanbul, ikas e-ticaret kurulumu, e-ticaret sitesi kurma, shopify tasarım, ikas uzmanı',
    canonical: 'https://www.samer.life/eticaret-site-kurulumu',
    lang: 'tr',
    content: `
      <h1>E-Ticaret Site Kurulumu İstanbul | Shopify & İKAS Uzmanı — Samer</h1>
      <p>Ben, markanızın ihtiyaçlarına en uygun altyapıyı (Shopify veya İKAS) belirleyerek A'dan Z'ye anahtar teslim e-ticaret kurulum hizmetleri sunuyorum.</p>
      <h2>E-Ticaret Kurulum Kapsamında Neler Yapıyorum?</h2>
      <ul>
        <li><strong>Altyapı Seçimi & Kurulumu:</strong> Shopify veya İKAS altyapısının kurulumu.</li>
        <li><strong>Özel Tema & UX/UI Tasarımı:</strong> Mobil cihazlarda hızlı yüklenen, sepet terki oranını düşürmek üzere optimize edilmiş arayüz tasarımı.</li>
        <li><strong>Ödeme & Kargo Entegrasyonları:</strong> iyzico, PayTR ve kargo entegrasyonları.</li>
      </ul>
    `
  },
  'eticaret-optimizasyon': {
    title: 'E-Ticaret Optimizasyon | Dönüşüm ve Satış Artışı — Samer',
    description: 'E-ticaret mağazanızın dönüşüm oranını artırın. A/B test, hız optimizasyonu ve UX iyileştirmeleriyle satışlarınızı büyütün.',
    keywords: 'e-ticaret optimizasyon, dönüşüm oranı artırma, shopify hız optimizasyon, core web vitals, e-ticaret seo',
    canonical: 'https://www.samer.life/eticaret-optimizasyon',
    lang: 'tr',
    content: `
      <h1>E-Ticaret Optimizasyon | Dönüşüm ve Satış Artışı — Samer</h1>
      <p>Google LCP, CLS ve INP metriklerinizi yeşil bölgeye (90+) taşımak için CSS, JS ve resim yükleme optimizasyonları yapıyorum.</p>
    `
  },
  'urun-gorsel-ve-icerik': {
    title: 'Ürün Görseli ve İçerik Üretimi | E-Ticaret — Samer',
    description: 'Profesyonel ürün fotoğrafı ve SEO uyumlu içerik üretimi. E-ticaret mağazanız için dönüştüren görseller ve açıklamalar.',
    keywords: 'ürün fotoğrafı düzenleme, yapay zeka ürün görseli, ürün açıklaması yazma, e-ticaret içerik, seo ürün açıklaması',
    canonical: 'https://www.samer.life/urun-gorsel-ve-icerik',
    lang: 'tr',
    content: `
      <h1>Ürün Görseli ve İçerik Üretimi | E-Ticaret — Samer</h1>
      <p>Ürünlerinizin ham fotoğraflarını yapay zeka ile şık, konsept ve gerçekçi arka planlara yerleştiriyorum ve SEO uyumlu ürün açıklamaları yazıyorum.</p>
    `
  },
  'stok-ve-depo-sistemi': {
    title: 'Stok ve Depo Yönetim Sistemi | Otomasyon — Samer',
    description: 'Stok takibi ve depo yönetimini otomatikleştirin. Özel yazılım çözümleriyle manuel hatalardan kurtulun.',
    keywords: 'stok yönetim sistemi, shopify ikas entegrasyon, trendyol stok senkronizasyon, depo otomasyon, erp entegrasyon',
    canonical: 'https://www.samer.life/stok-ve-depo-sistemi',
    lang: 'tr',
    content: `
      <h1>Stok ve Depo Yönetim Sistemi | Otomasyon — Samer</h1>
      <p>Trendyol, Hepsiburada ve Shopify API'leri entegre edilerek, sipariş oluştuğu anda tüm kanallarda stok miktarını güncelleyen webhook altyapısı kuruyorum.</p>
    `
  },
  'ozel-yazilim-gelistirme': {
    title: 'Özel Yazılım Geliştirme İstanbul | Full-Stack — Samer',
    description: 'React, Next.js ve Node.js ile özel web uygulamaları. İstanbul merkezli freelance full-stack geliştirici.',
    keywords: 'özel yazılım geliştirme istanbul, full stack geliştirici istanbul, react next.js freelance, api geliştirme',
    canonical: 'https://www.samer.life/ozel-yazilim-gelistirme',
    lang: 'tr',
    content: `
      <h1>Özel Yazılım Geliştirme İstanbul | Full-Stack — Samer</h1>
      <p>React, Next.js ve Node.js ile modern, hızlı ve güvenli özel web uygulamaları ve API servisleri geliştiriyorum.</p>
    `
  },
  'aylik-yonetim': {
    title: 'Aylık E-Ticaret Yönetimi',
    description: 'E-ticaret sitenizin aylık yönetimi: ürün güncellemeleri, kampanya yönetimi, teknik bakım ve SEO raporlamaları.',
    keywords: 'aylık e-ticaret yönetimi, shopify bakım, ikas yönetim, e-ticaret danışmanlık aylık',
    canonical: 'https://www.samer.life/aylik-yonetim',
    lang: 'tr',
    content: `
      <h1>Aylık E-Ticaret Yönetimi</h1>
      <p>Sitenizin aylık yönetimini, bakımını ve raporlamasını bana devrederek işinizi büyütmeye odaklanabilirsiniz.</p>
    `
  },
  'hizmetler': {
    title: 'E-Ticaret & Özel Yazılım Geliştirme Hizmetleri | Samer Allaham',
    description: 'Shopify ve İKAS kurulumu, hız optimizasyonu, yapay zeka ürün içeriği, pazaryeri stok entegrasyonu ve kurumsal web sitesi geliştirme hizmetlerinin detayları.',
    keywords: 'e-ticaret hizmetleri, shopify kurulum, ikas hız optimizasyon, stok entegrasyonu, yapay zeka e-ticaret, web yazılım, api geliştirme',
    canonical: 'https://www.samer.life/hizmetler',
    lang: 'tr',
    content: `<h1>E-Ticaret & Yazılım Çözümleri Hizmetlerim</h1><p>Samer Allaham olarak, e-ticaret mağazanızın satış performansını artıracak ve iş süreçlerinizi otomatikleştirecek profesyonel teknik çözümler geliştiriyorum.</p>`
  },
  'iletisim': {
    title: 'İletişim & Ücretsiz E-Ticaret Analizi | Samer Allaham',
    description: 'Shopify, İKAS veya özel yazılım projeniz için benimle iletişime geçin. Form veya WhatsApp üzerinden hemen yazın, projenizi birlikte planlayalım.',
    keywords: 'e-ticaret danışmanlık iletişim, shopify teklif al, ikas entegrasyon fiyat, samer allaham iletişim',
    canonical: 'https://www.samer.life/iletisim',
    lang: 'tr',
    content: `<h1>İletişim & Proje Teklif Formu</h1><p>E-ticaret mağazanızın dönüşüm oranlarını artırmak, stoklarınızı otomatikleştirmek ya da sıfırdan profesyonel bir mağaza kurmak istiyorsanız hemen iletişime geçin.</p>`
  },
  'hakkimda': {
    title: 'Hakkımda — E-Ticaret & API Çözümleri Geliştiricisi | Samer Allaham',
    description: 'Samer Allaham kimdir? E-ticaret platformları, API entegrasyonu, yapay zeka destekli içerik ve tam yığın web geliştirme konularındaki 5+ yıllık tecrübem ve yeteneklerim.',
    keywords: 'samer allaham kimdir, e-ticaret geliştirici, shopify uzmanı, ikas uzmanı, full stack developer',
    canonical: 'https://www.samer.life/hakkimda',
    lang: 'tr',
    content: `<h1>Samer Allaham Hakkında</h1><p>Merhaba, ben Samer Allaham. 5 yılı aşkın süredir e-ticaret ekosisteminde yazılımlar ve entegrasyonlar geliştiren bir tam yığın (full-stack) geliştiriciyim.</p>`
  },
  'basari-hikayeleri': {
    title: 'Müşteri Başarı Hikayeleri & Vaka Analizleri | Samer Allaham',
    description: 'Gerçek verilerle doğrulanabilir e-ticaret başarı hikayeleri. Shopify checkout optimizasyonları, İKAS hız geliştirmeleri ve stok entegrasyon vaka analizleri.',
    keywords: 'e-ticaret başarı hikayeleri, shopify vaka analizi, dönüşüm oranı artırma örnekleri, ikas hız geliştirme',
    canonical: 'https://www.samer.life/basari-hikayeleri',
    lang: 'tr',
    content: `<h1>Müşteri Başarı Hikayeleri</h1><p>Birlikte çalıştığımız e-ticaret markalarının elde ettiği somut ve doğrulanabilir başarı metriklerinden bazıları.</p>`
  },
  'blog': {
    title: 'E-Ticaret Blogu, Shopify & İKAS Satış Artırma Rehberleri',
    description: 'E-ticarette sepet terkini azaltma yolları, sayfa açılış hızı artırma yöntemleri, Shopify ve İKAS satış stratejilerine dair güncel, pratik ve uzman rehberler.',
    keywords: 'e-ticaret blogu, shopify rehberi, ikas rehber, e-ticaret seo, sayfa hızı artırma, sepet terki önleme',
    canonical: 'https://www.samer.life/blog',
    lang: 'tr',
    content: `<h1>E-Ticaret & Satış Artırma Blogu</h1><p>E-ticaret mağazanızda dönüşüm oranlarını (CRO) yükseltmek ve SEO sıralamalarınızı geliştirmek için rehber yazılarım.</p>`
  },

  // ==========================================
  // ENGLISH PAGES (Prefix /en)
  // ==========================================
  'en': {
    title: 'E-Commerce Developer & Shopify Expert Turkey | Samer Allaham',
    description: 'I build high-performance Shopify and İKAS e-commerce stores. Conversion Rate Optimization (CRO), automated inventory APIs, and AI-powered product listing copy. Meet your e-commerce partner, Samer Allaham.',
    keywords: 'e-commerce developer Istanbul, Shopify expert Turkey, hire shopify developer, ecommerce website setup, conversion rate optimization, api integration developer',
    canonical: 'https://www.samer.life/en',
    lang: 'en',
    content: `
      <h1>E-Commerce Developer & Shopify Expert Turkey | Samer Allaham</h1>
      <p>Hello, I'm Samer Allaham — a professional full-stack developer specializing in Shopify and İKAS. I engineer high-speed, high-converting e-commerce systems.</p>
      <h2>My Services</h2>
      <ul>
        <li><strong>E-Commerce Setup:</strong> Shopify & İKAS premium storefront custom development, payment gateways and local courier configurations.</li>
        <li><strong>Speed & Conversion Optimization:</strong> Code cleanup, asset compression, and checkout optimization to achieve 90+ Core Web Vitals.</li>
        <li><strong>Multichannel Inventory Automation:</strong> Custom Node.js & Python middleware linking ERP/accounting tools directly to your online store channels.</li>
      </ul>
      <h2>Customer Reviews</h2>
      <ul>
        <li><strong>Ahmet Y. (AIO Coffee CEO):</strong> "We worked with Samer on checkout and speed optimization. Our conversion rate increased by 35%. His work discipline and technical knowledge is excellent."</li>
        <li><strong>Elif K. (Moda Butiği Founder):</strong> "He migrated our WordPress site to İKAS seamlessly. Our page load speed dropped to 1.1s. Thanks a lot for his support and guidance."</li>
        <li><strong>Omar B. (Global E-Commerce Manager):</strong> "He developed the inventory synchronization software between Shopify and Trendyol. Our penalties caused by manual errors are completely gone."</li>
      </ul>
    `
  },
  'en/services': {
    title: 'E-Commerce Custom Development Services | Samer Allaham',
    description: 'Explore Shopify setup, conversion rate optimization (CRO), custom API integrations, and AI product listing copy options designed to grow your business.',
    keywords: 'shopify services turkey, speed optimization shopify, inventory api development, headless commerce services',
    canonical: 'https://www.samer.life/en/services',
    lang: 'en',
    content: `<h1>E-Commerce Development Services</h1><p>Engineered technical solutions designed to scale your store operations and boost checkouts.</p>`
  },
  'en/ecommerce-setup': {
    title: 'Shopify & İKAS E-Commerce Setup | Samer Allaham',
    description: 'Get custom e-commerce setup on Shopify or İKAS. Responsive designs, custom app configurations, Stripe/PayPal payment integrations, and technical SEO structure.',
    keywords: 'shopify development service, ikas expert, setup shopify store, premium ecommerce setup, stripe integration',
    canonical: 'https://www.samer.life/en/ecommerce-setup',
    lang: 'en',
    content: `
      <h1>Shopify & İKAS E-Commerce Setup</h1>
      <p>I build custom, premium storefronts on Shopify and İKAS optimized to deliver modern shopping experiences.</p>
    `
  },
  'en/ecommerce-optimization': {
    title: 'E-Commerce Speed Optimization & CRO | Samer Allaham',
    description: 'Optimize page speed and boost user experience. Elevate your Google Core Web Vitals (LCP, CLS, INP) scores to increase sales and search visibility.',
    keywords: 'shopify speed optimization, core web vitals fix, CRO for shopify, checkout optimization, page speed service',
    canonical: 'https://www.samer.life/en/ecommerce-optimization',
    lang: 'en',
    content: `<h1>E-Commerce Speed & CRO</h1><p>Improve page response times and checkout conversions by cutting scripts latency and boosting page performance.</p>`
  },
  'en/product-visuals-content': {
    title: 'AI Product Background Visuals & SEO Descriptions | Samer Allaham',
    description: 'Transform raw product photos into studio-quality background scenes using generative AI. Get high-ranking SEO-rich product descriptions for Google and LLM searches.',
    keywords: 'ai product photo editor, seo copywriting ecommerce, product feed optimization, google shopping feed',
    canonical: 'https://www.samer.life/en/product-visuals-content',
    lang: 'en',
    content: `<h1>AI Product Visuals & Copywriting</h1><p>Automate background replacement and write compelling descriptions that search engines and AI assistants rank first.</p>`
  },
  'en/inventory-stock-automation': {
    title: 'Multichannel Stock & Inventory API Automation | Samer Allaham',
    description: 'Synchronize inventory in real-time between Shopify, İKAS, and marketplaces via custom Node.js/Python APIs. Connect ERP, Paraşüt, or Logo billing systems.',
    keywords: 'inventory sync api, shopify marketplace integration, custom erp integration, multi-channel stock sync',
    canonical: 'https://www.samer.life/en/inventory-stock-automation',
    lang: 'en',
    content: `<h1>Inventory API Sync & Automation</h1><p>Prevent overselling by linking your retail stock quantities directly to your digital channels instantly.</p>`
  },
  'en/monthly-management': {
    title: 'Monthly E-Commerce Management & Tech Support | Samer Allaham',
    description: 'Delegate technical tasks. Monthly catalog updates, campaign and discount code setups, daily backups, speed monitoring, and organic SEO reports.',
    keywords: 'shopify retainer developer, ecommerce maintenance support, website management service',
    canonical: 'https://www.samer.life/en/monthly-management',
    lang: 'en',
    content: `<h1>Monthly E-Commerce retainer support</h1><p>Full technical and operational support to keep your store updated, fast, and secure daily.</p>`
  },
  'en/case-studies': {
    title: 'E-Commerce Growth Case Studies & Impact | Samer Allaham',
    description: 'Verifiable success stories showing conversion rate increases, headless transitions, speed improvements, and marketplace API sync integrations.',
    keywords: 'shopify case studies, conversion optimization results, ecommerce growth results',
    canonical: 'https://www.samer.life/en/case-studies',
    lang: 'en',
    content: `<h1>Client Case Studies</h1><p>Check out how my custom code directly optimized speed, sales, and operations for retail brands.</p>`
  },
  'en/blog': {
    title: 'E-Commerce Blog: Shopify Sales & Speed Guides',
    description: 'Articles on reducing cart abandonment, fixing page speed, optimizing checkout experiences, and structuring product feeds.',
    keywords: 'ecommerce blog, shopify coding tips, speed guides, cro tips',
    canonical: 'https://www.samer.life/en/blog',
    lang: 'en',
    content: `<h1>E-Commerce Growth Blog</h1><p>Guides and coding tutorials on scaling e-commerce conversion, SEO, and developer setups.</p>`
  },
  'en/about': {
    title: 'About Samer Allaham | Full-Stack E-Commerce Developer',
    description: 'Learn about Samer Allaham, an Istanbul-based full-stack developer with 5+ years of experience delivering APIs, databases, and custom e-commerce integrations.',
    keywords: 'samer allaham developer bio, full stack developer istanbul, shopify partner developer',
    canonical: 'https://www.samer.life/en/about',
    lang: 'en',
    content: `<h1>About Samer Allaham</h1><p>Full-stack developer engineering robust API pipelines and conversion-driven e-commerce systems.</p>`
  },
  'en/contact': {
    title: 'Contact Samer Allaham | Get Custom E-Commerce Quote',
    description: 'Discuss your Shopify, İKAS, or custom API project. Submit the proposal form or connect on WhatsApp for a free site performance analysis.',
    keywords: 'hire developer whatsapp, custom software project quote, contact shopify expert',
    canonical: 'https://www.samer.life/en/contact',
    lang: 'en',
    content: `<h1>Get in Touch</h1><p>Request a quote or get a free audit for your current store setup.</p>`
  },

  // ==========================================
  // ARABIC PAGES (Prefix /ar)
  // ==========================================
  'ar': {
    title: 'تصميم متجر شوبيفاي في تركيا & خبير إيكاس | سامر اللحام',
    description: 'مبرمج مواقع تجارة إلكترونية شوبيفاي وإيكاس. تسريع المواقع وزيادة المبيعات، أتمتة المستودعات والمخزون، وتصميم متاجر احترافية في تركيا للشركات العربية.',
    keywords: 'تصميم متجر شوبيفاي في تركيا, خبير شوبيفاي تركيا, برمجة متجر الكتروني, زيادة مبيعات المتجر, ربط المستودعات, سامر اللحام',
    canonical: 'https://www.samer.life/ar',
    lang: 'ar',
    content: `
      <h1>تصميم متجر شوبيفاي في تركيا & خبير إيكاس | سامر اللحام</h1>
      <p>مرحباً، أنا سامر اللحام — مبرمج ومطور متاجر تجارة إلكترونية متخصص في منصات شوبيفاي وإيكاس. أبني أنظمة مبيعات متكاملة تزيد من أرباحك وتؤتمت عملياتك.</p>
      <h2>خدماتي البرمجية</h2>
      <ul>
        <li><strong>إنشاء المتاجر الإلكترونية (Shopify & İKAS):</strong> تصميم متاجر متوافقة بالكامل مع الجوال، مع دمج بوابات الدفع والشحن التركية والعالمية.</li>
        <li><strong>تسريع المتاجر الإلكترونية (CRO):</strong> تحسين مؤشرات سرعة الويب الأساسية لجوجل لتقليل هروب الزوار وزيادة التحويلات.</li>
        <li><strong>أتمتة المخزون والربط البرمجي:</strong> مزامنة المخزون فورياً بين موقعك والمنصات (Trendyol, Hepsiburada) وبرامج المحاسبة (Paraşüt, Logo).</li>
      </ul>
      <h2>آراء العملاء</h2>
      <ul>
        <li><strong>أحمد ي. (الرئيس التنفيذي لـ AIO Coffee):</strong> "عملنا مع سامر على تحسين سرعة الدفع وصفحة الدفع. ارتفع معدل التحويل لدينا بنسبة 35٪. انضباطه في العمل ومعرفته التقنية رائعة."</li>
        <li><strong>إليف ك. (مؤسسة متجر Moda Butiği):</strong> "لقد نقل موقعنا من ووردبريس إلى إيكاس بسلاسة تامة. انخفضت سرعة تحميل صفحتنا إلى 1.1 ثانية. شكراً جزيلاً لدعمه وتوجيهه."</li>
        <li><strong>عمر ب. (مدير العمليات التجارية العالمية):</strong> "قام بتطوير برنامج مزامنة المخزون بين شوبيفاي وترينديول. انتهت الغرامات الناتجة عن الأخطاء اليدوية تماماً."</li>
      </ul>
    `
  },
  'ar/services': {
    title: 'خدمات برمجة وتصميم المتاجر الإلكترونية | سامر اللحام',
    description: 'تعرف على خدماتنا تشمل تصميم متاجر شوبيفاي، تسريع المواقع، أتمتة الفواتير والمخزون، وكتابة محتوى المنتجات بالذكاء الاصطناعي.',
    keywords: 'خدمات سيو المتاجر, ربط الدفع شوبيفاي, تسريع متجر شوبيفاي, مطور تطبيقات تجارة الكترونية',
    canonical: 'https://www.samer.life/ar/services',
    lang: 'ar',
    content: `<h1>خدمات التجارة الإلكترونية</h1><p>حلول برمجية ذكية مصممة خصيصاً لزيادة أرباح المتاجر وتسهيل الإدارة التشغيلية اليومية.</p>`
  },
  'ar/shopify-setup-turkey': {
    title: 'تصميم متجر شوبيفاي في تركيا & إيكاس | سامر اللحام',
    description: 'خدمة تصميم متجر شوبيفاي أو إيكاس متكامل في تركيا. تهيئة بوابات الدفع مثل PayTR وiyzico، ربط شركات الشحن، وضبط السيو لتتصدر محركات البحث.',
    keywords: 'تصميم متجر شوبيفاي في تركيا, انشاء متجر الكتروني تركيا, تصميم متجر الكتروني ايكas, مطور شوبيفاي اسطنبول',
    canonical: 'https://www.samer.life/ar/shopify-setup-turkey',
    lang: 'ar',
    content: `
      <h1>تصميم متجر شوبيفاي في تركيا & إيكاس</h1>
      <p>أقوم ببناء متاجر إلكترونية فاخرة وعالية السرعة على منصات شوبيفاي وإيكاس تناسب جمهورك المستهدف وتضمن تجربة شراء سلسة.</p>
    `
  },
  'ar/ecommerce-optimization': {
    title: 'تسريع المتاجر الإلكترونية وزيادة معدل التحويل | سامر اللحام',
    description: 'تسريع متجر شوبيفاي وإيكاس لتحقيق درجات عالية في مؤشرات Core Web Vitals لجوجل. تقليل السلات المتروكة ورفع أرباح الإعلانات.',
    keywords: 'تسريع متجر شوبيفاي, زيادة مبيعات المتجر, تقليل السلات المتروكة, تحسين سرعة ايكاس',
    canonical: 'https://www.samer.life/ar/ecommerce-optimization',
    lang: 'ar',
    content: `<h1>تسريع المواقع وزيادة المبيعات (CRO)</h1><p>حلول تقنية ذكية لضغط الملفات وتسريع استجابة الخوادم بما يضمن عدم خسارة أي عميل بسبب بطء التصفح.</p>`
  },
  'ar/product-content-ai': {
    title: 'صور المنتجات بالذكاء الاصطناعي وكتابة السيو | سامر اللحام',
    description: 'معالجة وتعديل صور منتجاتك بالذكاء الاصطناعي لتصبح بجودة استوديو احترافية. كتابة أوصاف منتجات جذابة ومهيأة للظهور بجوجل ومحركات AI.',
    keywords: 'تعديل الصور بالذكاء الاصطناعي, كتابة وصف المنتجات سيو, تهيئة المنتجات لمحركات البحث',
    canonical: 'https://www.samer.life/ar/product-content-ai',
    lang: 'ar',
    content: `<h1>محتوى وصور المنتجات بالذكاء الاصطناعي</h1><p>توفير تكاليف استوديوهات التصوير الباهظة عبر الذكاء الاصطناعي مع كتابة أوصاف تسويقية ذكية تضمن تصدرك بجوجل.</p>`
  },
  'ar/stock-inventory-system': {
    title: 'ربط وأتمتة مخزون المستودعات والمتاجر | سامر اللحام',
    description: 'ربط ومزامنة المخزون تلقائياً وفورياً بين شوبيفاي وإيكاس والمنصات (Trendyol, Hepsiburada) والـ ERP (باراشوت، لوغو) عبر واجهات API خاصة.',
    keywords: 'برنامج مزامنة المخزون, ربط المتاجر بالمنصات, برمجة ربط الـ ERP, اتصالات API مخصصة',
    canonical: 'https://www.samer.life/ar/stock-inventory-system',
    lang: 'ar',
    content: `<h1>ربط وأتمتة مخزون المتاجر</h1><p>برمجة لوحات تحكم وحلول ربط ذكية تلغي العمل اليدوي وتحدث بيانات الكميات عبر قنوات البيع بثوانٍ لمنع الأخطاء.</p>`
  },
  'ar/monthly-ecommerce-management': {
    title: 'إدارة المتجر الإلكتروني التقنية والدعم الشهري | سامر اللحام',
    description: 'تفرغ للمبيعات ودع الإدارة التقنية لمتجرك علينا. إضافة منتجات، إعداد خصومات وحملات، نسخ احتياطي، ومراقبة سرعة وسيو المتجر شهرياً.',
    keywords: 'إدارة متاجر شوبيفاي, دعم فني شوبيفاي شهري, صيانة مواقع الويب',
    canonical: 'https://www.samer.life/ar/monthly-ecommerce-management',
    lang: 'ar',
    content: `<h1>إدارة المتاجر والدعم التقني الشهري</h1><p>توفير رعاية تقنية وصيانة مستمرة لمتجرك لضمان تحديثه وحمايته وسرعته على مدار الساعة.</p>`
  },
  'ar/case-studies': {
    title: 'قصص نجاح ومشاريع سابقة بالتجارة الإلكترونية | سامر اللحام',
    description: 'تصفح دراسات حالة موثقة لزيادة مبيعات المتاجر، تسريع المواقع، وأتمتة المخزون لعلامات تجارية حقيقية.',
    keywords: 'مشاريع سابقة شوبيفاي, دراسات حالة متاجر تركيا, نجاح تجارة الكترونية',
    canonical: 'https://www.samer.life/ar/case-studies',
    lang: 'ar',
    content: `<h1>قصص نجاح عملائنا</h1><p>كيف ساهمت حلولنا البرمجية المخصصة في خفض تكاليف التشغيل وزيادة معدل الشراء للمتاجر.</p>`
  },
  'ar/blog': {
    title: 'مدونة التجارة الإلكترونية | نصائح شوبيفاي وإيكاس',
    description: 'مقالات وأدلة عملية حول كيفية تقليل السلات المتروكة، تسريع مواقع شوبيفاي، وضبط سيو المنتجات لزيادة المبيعات.',
    keywords: 'مدونة شوبيفاي بالعربي, سيو المتاجر الالكترونية, نصائح زيادة المبيعات',
    canonical: 'https://www.samer.life/ar/blog',
    lang: 'ar',
    content: `<h1>مدونة نمو التجارة الإلكترونية</h1><p>أدلة تقنية وشروحات برمجية عملية لمساعدتك في قيادة متجرك نحو الصدارة البرمجية والبيعية.</p>`
  },
  'ar/about': {
    title: 'من هو سامر اللحام | مبرمج ومطور متاجر إلكترونية',
    description: 'تعرف على المبرمج سامر اللحام، خبرة تزيد عن 5 سنوات في برمجة قواعد البيانات وتطوير المتاجر الإلكترونية وبناء واجهات الربط البرمجي APIs.',
    keywords: 'سامر اللحام مطور مواقع, مبرمج شوبيفاي اسطنبول, مطور ويب كامل',
    canonical: 'https://www.samer.life/ar/about',
    lang: 'ar',
    content: `<h1>نبذة عن سامر اللحام</h1><p>مطور برمجيات متكامل (Full-stack) مكرس جهوده لبناء أنظمة ويب آمنة ومتاجر إلكترونية تحقق أعلى العوائد الممكنة للعلامات التجارية.</p>`
  },
  'ar/contact': {
    title: 'اتصل بنا | احصل على عرض سعر لمتجرك الإلكتروني',
    description: 'تواصل مع الخبير سامر اللحام لمناقشة مشروع متجرك أو الربط البرمجي. راسلنا عبر الواتساب أو املأ النموذج لاستلام تحليل مجاني لموقعك.',
    keywords: 'تواصل مع مبرمج واتساب, اسعار تصميم متجر شوبيفاي, استشارة تجارة الكترونية مجانية',
    canonical: 'https://www.samer.life/ar/contact',
    lang: 'ar',
    content: `<h1>تواصل معنا اليوم</h1><p>اطرح أسئلتك أو اطلب تحليل أداء مجاني لمتجرك الحالي للبدء في خطة التطوير.</p>`
  }
};

// Define blog posts configurations (6 posts * 3 languages = 18 pages)
const blogPostsList = [
  'eticaret-sitem-var-ama-satis-yok-sorun-nerede',
  'urunlerim-goruntuleniyor-ama-satilmiyor-ne-yapmaliyim',
  'eticarette-ilk-5-saniye-musteri-neden-terk-ediyor',
  'sepete-ekleniyor-ama-satilmiyor-sorunun-kaynagi-ne',
  'e-ticaret-web-tasarim-rehberi-2026',
  'profesyonel-web-tasarim-ve-websitesi-yaptirma-rehberi'
];

const blogDetails = {
  tr: {
    'eticaret-sitem-var-ama-satis-yok-sorun-nerede': {
      title: 'E-Ticaret Sitem Var Ama Satış Yok, Sorun Nerede? | Samer Allaham',
      description: 'E-ticaret sitenizde trafik olduğu halde satış yapamıyorsanız bunun teknik ve tasarımsal sebeplerini analiz ediyor, çözüm yollarını sunuyorum.',
      content: `<h1>E-Ticaret Sitem Var Ama Satış Yok, Sorun Nerede?</h1><p>Analiz etmeniz gereken kritik noktalar: 1. Yavaş yüklenme süreleri, 2. Güven eksikliği, 3. Karmaşık satın alma adımları.</p>`
    },
    'urunlerim-goruntuleniyor-ama-satilmiyor-ne-yapmaliyim': {
      title: 'Ürünlerim Görüntüleniyor Ama Satılmıyor, Ne Yapmalıyım? | Samer Allaham',
      description: 'Ürün detay sayfasına ziyaretçi geldiği halde sipariş alamıyorsanız ürün görselleri, açıklamalar ve CRO hatalarını nasıl gidereceğinizi öğrenin.',
      content: `<h1>Ürünlerim Görüntüleniyor Ama Satılmıyor, Ne Yapmalıyım?</h1><p>Ürün detay sayfanızda kontrol edin: 1. Düşük kaliteli görseller, 2. Yetersiz açıklamalar, 3. CTA butonunun belirsizliği.</p>`
    },
    'eticarette-ilk-5-saniye-musteri-neden-terk-ediyor': {
      title: 'E-Ticarette İlk 5 Saniye: Müşteri Neden Terk Ediyor? | Samer Allaham',
      description: 'Sitenize giren ziyaretçilerin ilk 5 saniyede çıkış yapma (bounce rate) nedenleri ve kullanıcı deneyimi (UX) çözüm önerileri.',
      content: `<h1>E-Ticarette İlk 5 Saniye: Müşteri Neden Terk Ediyor?</h1><p>Hemen çıkma nedenleri: 1. İlk ekran karmaşası, 2. Mobil uyumluluk hataları, 3. Agresif popuplar.</p>`
    },
    'sepete-ekleniyor-ama-satilmiyor-sorunun-kaynagi-ne': {
      title: 'Sepete Ekleniyor Ama Satılmıyor, Sorunun Kaynağı Ne? | Samer Allaham',
      description: 'Sepete ekleme yapıldığı halde ödeme adımında yaşanan satış kayıplarının (Cart Abandonment) tespiti ve CRO iyileştirmeleri.',
      content: `<h1>Sepete Ekleniyor Ama Satılmıyor, Sorunun Kaynağı Ne?</h1><p>Ödeme adımı iyileştirmeleri: 1. Sürpriz kargo ücretlerini kaldırmak, 2. Misafir ödemeyi açmak, 3. Güven logoları eklemek.</p>`
    },
    'e-ticaret-web-tasarim-rehberi-2026': {
      title: 'E-Ticaret Web Tasarım Rehberi: Satış Yapan Online Mağaza Tasarımı | Samer Allaham',
      description: 'Satışlarınızı artıran e-ticaret web tasarım prensipleri, mobil öncelikli kullanıcı deneyimi (UX) ve 2026 trendleri ile dönüşüm odaklı online mağaza kurma rehberi.',
      content: `<h1>E-Ticaret Web Tasarım Rehberi: Satış Yapan Online Mağaza Tasarımı</h1><p>Shopify ve İKAS ile dönüşüm odaklı e-ticaret web tasarım prensipleri, mobil uyumluluk ve hızlı ödeme çözümleri.</p>`
    },
    'profesyonel-web-tasarim-ve-websitesi-yaptirma-rehberi': {
      title: 'Profesyonel Web Tasarım ve Websitesi Yaptırma Rehberi 2026 | Samer Allaham',
      description: 'İşletmeniz için profesyonel web tasarım yaptırırken dikkat edilmesi gerekenler, SEO altyapısı, React & Next.js modern kodlama ve websitesi maliyet analizi.',
      content: `<h1>Profesyonel Web Tasarım ve Websitesi Yaptırma Rehberi 2026</h1><p>Modern React & Next.js altyapıları ile kurumsal web tasarım, SEO dostu kodlama ve performans çözümleri.</p>`
    }
  },
  en: {
    'eticaret-sitem-var-ama-satis-yok-sorun-nerede': {
      title: 'I Have Traffic But No Sales, What Is Wrong? | Samer Allaham',
      description: 'Analyze why your e-commerce store is attracting visitors but failing to convert them into paying customers. CRO and technical fixes.',
      content: `<h1>I Have Traffic But No Sales, What Is Wrong?</h1><p>Key issues: 1. Slow page speeds, 2. Lack of trust signals, 3. Overly complex checkout flows.</p>`
    },
    'urunlerim-goruntuleniyor-ama-satilmiyor-ne-yapmaliyim': {
      title: 'Products are Viewed But Not Selling, What to Do? | Samer Allaham',
      description: 'Improve product page conversion rate. How high-quality photos, clear specs, and noticeable add-to-cart buttons drive sales.',
      content: `<h1>Products are Viewed But Not Selling, What to Do?</h1><p>Things to audit: 1. Low resolution product photos, 2. Poor product specs, 3. Unclear call-to-actions.</p>`
    },
    'eticarette-ilk-5-saniye-musteri-neden-terk-ediyor': {
      title: 'The First 5 Seconds: Why Users Abandon E-Stores | Samer Allaham',
      description: 'Identify bounce rate factors on your landing pages and discover UX layouts that keep visitors browsing your store.',
      content: `<h1>The First 5 Seconds: Why Users Abandon E-Stores</h1><p>Common bounce reasons: 1. Unclear hero message, 2. Poor mobile layout, 3. Too many popups.</p>`
    },
    'sepete-ekleniyor-ama-satilmiyor-sorunun-kaynagi-ne': {
      title: 'Added to Cart But Not Buying? Checkout CRO | Samer Allaham',
      description: 'Reduce cart abandonment rates. Discover checkout optimizations like guest buying, transparent shipping fees, and local payment methods.',
      content: `<h1>Added to Cart But Not Buying? Checkout CRO</h1><p>Reduce abandonment: 1. Hide unexpected shipping charges, 2. Enable checkout without registering, 3. Display secure gateway icons.</p>`
    },
    'e-ticaret-web-tasarim-rehberi-2026': {
      title: 'E-Commerce Web Design Guide: High-Converting Stores | Samer Allaham',
      description: 'E-commerce web design principles, mobile-first UX layouts, and 2026 trends to scale your online shop checkouts.',
      content: `<h1>E-Commerce Web Design Guide</h1><p>Conversion-driven web design for Shopify & İKAS platforms.</p>`
    },
    'profesyonel-web-tasarim-ve-websitesi-yaptirma-rehberi': {
      title: 'Professional Web Design & Website Guide 2026 | Samer Allaham',
      description: 'Key factors when hiring for professional web design, Technical SEO foundation, and modern React/Next.js stack benefits.',
      content: `<h1>Professional Web Design & Website Guide</h1><p>Modern React & Next.js web design solutions for corporate brands.</p>`
    }
  },
  ar: {
    'eticaret-sitem-var-ama-satis-yok-sorun-nerede': {
      title: 'لماذا يتصفح الزوار متجري ولا يشترون؟ | سامر اللحام',
      description: 'تحليل وحلول تقنية لعلاج ضعف المبيعات رغم وجود زيارات للمتجر الإلكتروني. تحسين معدل الشراء وسرعة التصفح.',
      content: `<h1>لماذا يتصفح الزوار متجري ولا يشترون؟</h1><p>نقاط الخلل الأساسية: 1. بطء تحميل الصفحات، 2. غياب وسائل الأمان، 3. تعقيد خطوات الدفع.</p>`
    },
    'urunlerim-goruntuleniyor-ama-satilmiyor-ne-yapmaliyim': {
      title: 'المنتج يحصد مشاهدات دون أي طلبات، ما الحل؟ | سامر اللحام',
      description: 'كيفية تحسين صفحة المنتج (Product Page) لزيادة المبيعات عبر صور احترافية، أوصاف جذابة، وتوضيح زر الشراء.',
      content: `<h1>المنتج يحصد مشاهدات دون أي طلبات، ما الحل؟</h1><p>راجع التالي في صفحة المنتج: 1. جودة الصور، 2. كفاية الأوصاف والمقاسات، 3. وضوح زر أضف للسلة.</p>`
    },
    'eticarette-ilk-5-saniye-musteri-neden-terk-ediyor': {
      title: 'أول 5 ثوانٍ بالمتجر: لماذا يخرج العميل سريعاً؟ | سامر اللحام',
      description: 'علاج مشكلة معدل الارتداد السريع (Bounce Rate) لزوار المتاجر الإلكترونية وتعديل واجهات المستخدم للجوال.',
      content: `<h1>أول 5 ثوانٍ بالمتجر: لماذا يخرج العميل سريعاً؟</h1><p>أسباب الخروج السريع: 1. غموض محتوى الشاشة الأولى، 2. مشاكل التصفح بالجوال، 3. النوافذ المنبثقة المزعجة.</p>`
    },
    'e-ticaret-web-tasarim-rehberi-2026': {
      title: 'دليل تصميم مواقع التجارة الإلكترونية | سامر اللحام',
      description: 'مبادئ تصميم المتاجر الإلكترونية لزيادة المبيعات، واجهات الجوال السريعة، وأحدث التوجهات لعام 2026.',
      content: `<h1>دليل تصميم مواقع التجارة الإلكترونية</h1><p>حلول تصميم متاجر شوبيفاي وإيكاس لزيادة المبيعات والتحويلات.</p>`
    },
    'profesyonel-web-tasarim-ve-websitesi-yaptirma-rehberi': {
      title: 'دليل تصميم المواقع الإلكترونية والويب 2026 | سامر اللحام',
      description: 'كل ما تحتاج معرفته حول تصميم موقع إلكتروني احترافي للشركات وتقنيات React & Next.js الحديثة.',
      content: `<h1>دليل تصميم المواقع الإلكترونية</h1><p>تصميم برمجيات ويب احترافية تناسب متطلبات محركات البحث والذكاء الاصطناعي.</p>`
    },
    'ar/blog/sepete-ekleniyor-ama-satilmiyor-sorunun-kaynagi-ne': {
      title: 'يضيفون السلة ولكن لا يكملون الدفع، ما السبب؟ | سامر اللحام',
      description: 'تحسين خطوات الدفع (Checkout) لتقليل نسبة السلات المتروكة وتسهيل الدفع كزائر دون تسجيل إجباري.',
      content: `<h1>يضيفون السلة ولكن لا يكملون الدفع، ما السبب؟</h1><p>علاج السلات المتروكة: 1. إظهار رسوم الشحن مبكراً، 2. الشراء كزائر سريع، 3. إظهار موثوقية بوابات الدفع.</p>`
    }
  }
};

// Build final flat routes configurations map
const allPages = {
  ...pages
};

// Programmatically register blog posts in 3 languages
blogPostsList.forEach(slug => {
  // Turkish blog path: /blog/slug
  if (blogDetails.tr[slug]) {
    allPages[`blog/${slug}`] = {
      ...blogDetails.tr[slug],
      canonical: `https://www.samer.life/blog/${slug}`,
      lang: 'tr'
    };
  }
  
  // English blog path: /en/blog/slug
  if (blogDetails.en[slug]) {
    allPages[`en/blog/${slug}`] = {
      ...blogDetails.en[slug],
      canonical: `https://www.samer.life/en/blog/${slug}`,
      lang: 'en'
    };
  }
  
  // Arabic blog path: /ar/blog/slug
  if (blogDetails.ar[slug]) {
    allPages[`ar/blog/${slug}`] = {
      ...blogDetails.ar[slug],
      canonical: `https://www.samer.life/ar/blog/${slug}`,
      lang: 'ar'
    };
  }
});

console.log(`Starting prerendering for ${Object.keys(allPages).length} routes...`);

// Helper to replace tag block (like <title> or <meta name="description">)
function replaceMetaTag(html, name, content) {
  const metaRegex = new RegExp(`<meta\\s+name="${name}"\\s+content="[^"]*"\\s*\\/?>`, 'i');
  if (metaRegex.test(html)) {
    return html.replace(metaRegex, `<meta name="${name}" content="${content}" />`);
  }
  const propRegex = new RegExp(`<meta\\s+property="og:${name}"\\s+content="[^"]*"\\s*\\/?>`, 'i');
  if (propRegex.test(html)) {
    return html.replace(propRegex, `<meta property="og:${name}" content="${content}" />`);
  }
  return html;
}

// Helper to resolve localized pathname prefix
function getLangPrefix(routePath) {
  if (routePath.startsWith('en/') || routePath === 'en') return 'en';
  if (routePath.startsWith('ar/') || routePath === 'ar') return 'ar';
  return 'tr';
}

const sitemapUrls = [];

Object.entries(allPages).forEach(([route, data]) => {
  let pageHtml = template;
  const pageLang = data.lang || getLangPrefix(route);
  const pageDir = pageLang === 'ar' ? 'rtl' : 'ltr';

  // 1. Force correct html language and direction attributes
  pageHtml = pageHtml.replace(/<html[^>]*>/i, `<html lang="${pageLang}" dir="${pageDir}">`);

  // 2. Replace title tags
  pageHtml = pageHtml.replace(/<title>.*?<\/title>/gi, `<title>${data.title}</title>`);
  pageHtml = pageHtml.replace(/<meta property="og:title" content="[^"]*"\s*\/?>/gi, `<meta property="og:title" content="${data.title}" />`);
  pageHtml = pageHtml.replace(/<meta name="twitter:title" content="[^"]*"\s*\/?>/gi, `<meta name="twitter:title" content="${data.title}" />`);

  // 3. Replace description tags
  pageHtml = replaceMetaTag(pageHtml, 'description', data.description);
  pageHtml = pageHtml.replace(/<meta property="og:description" content="[^"]*"\s*\/?>/gi, `<meta property="og:description" content="${data.description}" />`);
  pageHtml = pageHtml.replace(/<meta name="twitter:description" content="[^"]*"\s*\/?>/gi, `<meta name="twitter:description" content="${data.description}" />`);

  // 4. Replace keywords if specified
  if (data.keywords) {
    pageHtml = replaceMetaTag(pageHtml, 'keywords', data.keywords);
  }

  // 5. Replace canonical and Open Graph URL links
  pageHtml = pageHtml.replace(/<link rel="canonical" href="[^"]*"\s*\/?>/gi, `<link rel="canonical" href="${data.canonical}" />`);
  pageHtml = pageHtml.replace(/<meta property="og:url" content="[^"]*"\s*\/?>/gi, `<meta property="og:url" content="${data.canonical}" />`);

  // Calculate matching dynamic Hreflang URLs
  const relativePath = route === '' ? '/' : `/${route}`;
  // We need clean mapping for navigation hreflangs
  const trRoute = route.startsWith('en/') ? route.replace('en/', '') : (route.startsWith('ar/') ? route.replace('ar/', '') : route);
  
  // Custom lookup inside script matching the navigation map rules
  const lookupMap = {
    '/': { tr: '/', en: '/en', ar: '/ar' },
    '/services': { tr: '/hizmetler', en: '/en/services', ar: '/ar/services' },
    '/hizmetler': { tr: '/hizmetler', en: '/en/services', ar: '/ar/services' },
    '/web-design': { tr: '/web-tasarim', en: '/en/web-design', ar: '/ar/web-design' },
    '/web-tasarim': { tr: '/web-tasarim', en: '/en/web-design', ar: '/ar/web-design' },
    '/ecommerce-web-design': { tr: '/e-ticaret-web-tasarim', en: '/en/ecommerce-web-design', ar: '/ar/ecommerce-web-design' },
    '/e-ticaret-web-tasarim': { tr: '/e-ticaret-web-tasarim', en: '/en/ecommerce-web-design', ar: '/ar/ecommerce-web-design' },
    '/ecommerce-setup': { tr: '/eticaret-site-kurulumu', en: '/en/ecommerce-setup', ar: '/ar/shopify-setup-turkey' },
    '/shopify-setup-turkey': { tr: '/eticaret-site-kurulumu', en: '/en/ecommerce-setup', ar: '/ar/shopify-setup-turkey' },
    '/eticaret-site-kurulumu': { tr: '/eticaret-site-kurulumu', en: '/en/ecommerce-setup', ar: '/ar/shopify-setup-turkey' },
    '/ecommerce-optimization': { tr: '/eticaret-optimizasyon', en: '/en/ecommerce-optimization', ar: '/ar/ecommerce-optimization' },
    '/eticaret-optimizasyon': { tr: '/eticaret-optimizasyon', en: '/en/ecommerce-optimization', ar: '/ar/ecommerce-optimization' },
    '/product-visuals-content': { tr: '/urun-gorsel-ve-icerik', en: '/en/product-visuals-content', ar: '/ar/product-content-ai' },
    '/product-content-ai': { tr: '/urun-gorsel-ve-icerik', en: '/en/product-visuals-content', ar: '/ar/product-content-ai' },
    '/urun-gorsel-ve-icerik': { tr: '/urun-gorsel-ve-icerik', en: '/en/product-visuals-content', ar: '/ar/product-content-ai' },
    '/inventory-stock-automation': { tr: '/stok-ve-depo-sistemi', en: '/en/inventory-stock-automation', ar: '/ar/stock-inventory-system' },
    '/stock-inventory-system': { tr: '/stok-ve-depo-sistemi', en: '/en/inventory-stock-automation', ar: '/ar/stock-inventory-system' },
    '/stok-ve-depo-sistemi': { tr: '/stok-ve-depo-sistemi', en: '/en/inventory-stock-automation', ar: '/ar/stock-inventory-system' },
    '/monthly-management': { tr: '/aylik-yonetim', en: '/en/monthly-management', ar: '/ar/monthly-ecommerce-management' },
    '/monthly-ecommerce-management': { tr: '/aylik-yonetim', en: '/en/monthly-management', ar: '/ar/monthly-ecommerce-management' },
    '/aylik-yonetim': { tr: '/aylik-yonetim', en: '/en/monthly-management', ar: '/ar/monthly-ecommerce-management' },
    '/case-studies': { tr: '/basari-hikayeleri', en: '/en/case-studies', ar: '/ar/case-studies' },
    '/basari-hikayeleri': { tr: '/basari-hikayeleri', en: '/en/case-studies', ar: '/ar/case-studies' },
    '/blog': { tr: '/blog', en: '/en/blog', ar: '/ar/blog' },
    '/about': { tr: '/hakkimda', en: '/en/about', ar: '/ar/about' },
    '/hakkimda': { tr: '/hakkimda', en: '/en/about', ar: '/ar/about' },
    '/contact': { tr: '/iletisim', en: '/en/contact', ar: '/ar/contact' },
    '/iletisim': { tr: '/iletisim', en: '/en/contact', ar: '/ar/contact' }
  };

  let cleanPath = relativePath.endsWith('/') && relativePath.length > 1 ? relativePath.slice(0, -1) : relativePath;
  
  // Normalize language prefix to look up translations base path (e.g. /ar/services -> /services)
  let lookupPath = cleanPath;
  if (lookupPath.startsWith('/en/')) lookupPath = lookupPath.replace('/en/', '/');
  else if (lookupPath.startsWith('/ar/')) lookupPath = lookupPath.replace('/ar/', '/');
  else if (lookupPath === '/en' || lookupPath === '/ar') lookupPath = '/';

  let trUrlSuffix = cleanPath;
  let enUrlSuffix = cleanPath;
  let arUrlSuffix = cleanPath;

  if (lookupMap[lookupPath]) {
    trUrlSuffix = lookupMap[lookupPath].tr;
    enUrlSuffix = lookupMap[lookupPath].en;
    arUrlSuffix = lookupMap[lookupPath].ar;
  } else if (cleanPath.includes('/blog/')) {
    const slug = cleanPath.split('/blog/')[1];
    trUrlSuffix = `/blog/${slug}`;
    enUrlSuffix = `/en/blog/${slug}`;
    arUrlSuffix = `/ar/blog/${slug}`;
  } else {
    // Standard prefixes stripping fallback
    let stripped = cleanPath;
    if (stripped.startsWith('/en/')) stripped = stripped.replace('/en/', '/');
    else if (stripped.startsWith('/ar/')) stripped = stripped.replace('/ar/', '/');
    else if (stripped === '/en' || stripped === '/ar') stripped = '/';
    
    trUrlSuffix = stripped;
    enUrlSuffix = stripped === '/' ? '/en' : `/en${stripped}`;
    arUrlSuffix = stripped === '/' ? '/ar' : `/ar${stripped}`;
  }

  const trUrl = `https://www.samer.life${trUrlSuffix}`;
  const enUrl = `https://www.samer.life${enUrlSuffix}`;
  const arUrl = `https://www.samer.life${arUrlSuffix}`;

  const hreflangTags = `
  <link rel="alternate" hreflang="tr" href="${trUrl}" />
  <link rel="alternate" hreflang="en" href="${enUrl}" />
  <link rel="alternate" hreflang="ar" href="${arUrl}" />
  <link rel="alternate" hreflang="x-default" href="${trUrl}" />`;

  // Collect for Sitemap
  sitemapUrls.push(`  <url>
    <loc>https://www.samer.life${relativePath}</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
    <changefreq>${route.includes('blog/') ? 'monthly' : 'weekly'}</changefreq>
    <priority>${route === '' ? '1.0' : (route.includes('blog/') ? '0.7' : '0.85')}</priority>
    <xhtml:link rel="alternate" hreflang="tr" href="${trUrl}" />
    <xhtml:link rel="alternate" hreflang="en" href="${enUrl}" />
    <xhtml:link rel="alternate" hreflang="ar" href="${arUrl}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${trUrl}" />
  </url>`);

  // Inject hreflangs right after the canonical link
  const canonicalRegex = /<link rel="canonical" href="[^"]*"\s*\/?>/i;
  pageHtml = pageHtml.replace(canonicalRegex, `$&${hreflangTags}`);

  // 6. Replace the generic <noscript> block with page-specific rich HTML content
  const noscriptBlockRegex = /<noscript>\s*<div style="font-family:sans-serif;[\s\S]*?<\/noscript>/i;
  const newNoscriptBlock = `<noscript>
    <div style="font-family:sans-serif;max-width:900px;margin:auto;padding:2rem">
      ${data.content}
    </div>
  </noscript>`;
  pageHtml = pageHtml.replace(noscriptBlockRegex, newNoscriptBlock);

  // 7. Write the page to disk
  if (route === '') {
    // Root index.html (Turkish Home page)
    fs.writeFileSync(TEMPLATE_PATH, pageHtml, 'utf8');
    console.log('✓ Prerendered root page (dist/index.html)');
  } else {
    // Subpages go to dist/[route]/index.html
    const routeDir = path.join(BUILD_DIR, route);
    if (!fs.existsSync(routeDir)) {
      fs.mkdirSync(routeDir, { recursive: true });
    }
    fs.writeFileSync(path.join(routeDir, 'index.html'), pageHtml, 'utf8');
    console.log(`✓ Prerendered route: /${route} (dist/${route}/index.html)`);
  }
});

// Create 404.html as a copy of the main template for hosting fallback handling
fs.copyFileSync(TEMPLATE_PATH, path.join(BUILD_DIR, '404.html'));
console.log('✓ Generated dist/404.html from root template');

// Generate and save dist/sitemap.xml dynamically with all 44 routes and their respective hreflangs
const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${sitemapUrls.join('\n')}
</urlset>`;
fs.writeFileSync(path.join(BUILD_DIR, 'sitemap.xml'), sitemapXml, 'utf8');
console.log('✓ Dynamically generated dist/sitemap.xml with 44 localized URLs!');
console.log('Prerendering completed successfully!');
